apiVersion: v1
kind: ServiceAccount
metadata:
  name: akamai-operator-controller-manager
  namespace: akamai-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: akamai-operator-leader-election-role
  namespace: akamai-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akamai-operator-manager-role
rules:
- apiGroups:
  - akamai.com
  resources:
  - akamaiproperties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - akamai.com
  resources:
  - akamaiproperties/finalizers
  verbs:
  - update
- apiGroups:
  - akamai.com
  resources:
  - akamaiproperties/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akamai-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: akamai-operator-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: akamai-operator-leader-election-rolebinding
  namespace: akamai-operator-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akamai-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: akamai-operator-controller-manager
  namespace: akamai-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akamai-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akamai-operator-manager-role
subjects:
- kind: ServiceAccount
  name: akamai-operator-controller-manager
  namespace: akamai-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: akamai-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: akamai-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: akamai-operator-controller-manager
  namespace: akamai-operator-system